name: serinus_config
description: A module for Serinus applications that exposes the dotenv package allowing you to load environment variables from a .env file.
version: 0.1.0
repository: https://github.com/serinus_nest/serinus_config
homepage: https://docs.serinus.app
documentation: https://docs.serinus.app
topics:
  - server
  - httpserver
  - backend
  - web
  - dotenv

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dotenv: ^4.2.0
  serinus: ^0.2.1
  
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
